<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="538.013" tests="1" failures="2">
  <testsuite name="Root Suite" timestamp="2019-09-06T08:47:19" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="Credit Card 3-D Secure test" timestamp="2019-09-06T08:47:19" tests="1" file="/home/travis/shopware/custom/plugins/WirecardElasticEngine/Tests/Selenium/Payments/CreditCardThreeDTest.js" failures="2" time="538.013">
    <testcase name="Credit Card 3-D Secure test should check the credit card 3ds payment process" time="474.466" classname="should check the credit card 3ds payment process">
      <failure message="ETIMEDOUT connect ETIMEDOUT 208.52.180.207:80" type="Error"><![CDATA[Error: ETIMEDOUT connect ETIMEDOUT 208.52.180.207:80
    at ClientRequest.<anonymous> (node_modules/selenium-webdriver/http/index.js:258:15)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)]]></failure>
    </testcase>
    <testcase name="Credit Card 3-D Secure test &quot;after all&quot; hook" time="63.547" classname="&quot;after all&quot; hook">
      <failure message="Session not started or terminated" type="WebDriverError"><![CDATA[WebDriverError: Session not started or terminated
    at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:585:15)
    at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:551:13)
    at Executor.execute (node_modules/selenium-webdriver/lib/http.js:486:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)]]></failure>
    </testcase>
  </testsuite>
</testsuites>